[book]
authors = ["Dev Team<devteam@cyrup.ai>"]
language = "en"
multilingual = false
src = "docs"
title = "cyrup bootstrap: `setcyrup`"

[output.html]
git-repository-url = "https://github.com/cyrup-ai/get.cyrup.ai"
edit-url-template = "https://github.com/cyrup-ai/get.cyrup.ai/edit/main/{path}"
site-url = "https://get.cyrup.ai"
additional-css = ["theme/custom.css"]
default-theme = "navy"
prefer-dark-theme = true
